#!/bin/bash

# ----------------------------------------------------------------------------------
# build-ubuntu-k3s-template.sh
#
# Builds a Proxmox VM or template for K3s nodes based on an Ubuntu cloud image.
# Run this script directly on the Proxmox host.
#
# K3s installation mode is configurable:
#   - "agent"  : installs the K3s agent at first boot with dummy join values
#                (K3S_URL/K3S_TOKEN=dummy), service disabled and stopped.
#                Cluster join is handled at provisioning time via Cloud-Init
#                (e.g. by Karpenter), which overwrites /etc/rancher/k3s/config.yaml
#                and starts the k3s-agent service.
#   - "server" : installs K3s in server mode at first boot, left disabled/stopped.
#                Rarely what you want for a worker-node template — provided for
#                completeness / control-plane template reuse.
#   - "none"   : K3s is not installed at all. Use this if installation is fully
#                delegated to Cloud-Init at provisioning time.
#
# A Proxmox Cloud-Init drive (scsi1) and ciuser/cipassword/sshkeys are optional and
# disabled by default. Enable them only if you are NOT relying on a separate
# Cloud-Init ISO (e.g. generated by Karpenter) to configure networking, users
# and SSH access — using both at once is redundant and the two sources can conflict.
#
# Forked from the kproximate project template building example.
# Source: https://github.com/jedrw/kproximate/tree/main/examples
#
# Usage:
#   ./build-ubuntu-k3s-template.sh <codename> <vmid> [options]
#
# Options:
#   -c, --codename       NAME   Ubuntu release codename, e.g. noble, jammy
#   -i, --vmid           ID     Proxmox VM ID, e.g. 9000
#   -n, --name           NAME   Name of the resulting VM or template (default: ubuntu24-k3s-worker)
#   -t, --template              Convert the VM into a Proxmox template after build.
#                               Omit this flag to keep it as a regular, bootable VM instead
#                               (useful for bootstrapping a real cluster node directly,
#                               e.g. combined with --k3s-mode server/agent and --k3s-start).
#   -s, --storage        NAME   Proxmox storage name         (default: auto-detected)
#   -v, --vlan           TAG    VLAN tag for the NIC         (default: none)
#   -d, --disk           SIZE   Disk size, e.g. 30G          (default: 30G)
#   -b, --bridge         NAME   Network bridge               (default: vmbr0)
#
#   -m, --k3s-mode       MODE   K3s install mode: agent|server|none (default: none)
#   -k, --k3sversion     VER    K3s version, e.g. v1.35.2+k3s1      (default: latest stable)
#
#   --k3s-url            URL    (agent mode only) Real K3s server URL to join immediately at
#                               first boot, e.g. https://master.example.local:6443.
#                               If omitted, a dummy URL (https://dummy:6443) is used instead —
#                               the agent is installed but not actually joined to anything,
#                               for use with templates where the real join config is written
#                               later by Cloud-Init (e.g. by Karpenter). Requires --k3s-token
#                               and/or --k3s-agent-token to be set as well.
#   --k3s-token          TOKEN  (server mode) K3s server token to bootstrap with. If omitted,
#                               the K3s installer generates one itself (find it afterwards at
#                               /var/lib/rancher/k3s/server/token).
#                               (agent mode, with --k3s-url) The real server token to join with.
#                               Takes priority over --k3s-agent-token if both are set.
#   --k3s-agent-token    TOKEN  (server mode) K3s agent-only token, distinct from the server
#                               token (see https://docs.k3s.io/cli/token). If --k3s-token is
#                               also given in secure format (K10<ca-hash>::<user>:<password>),
#                               only the <password> portion is extracted and used as the
#                               agent token — this is valid per K3s docs, since the CA hash
#                               and username are set internally regardless.
#                               (agent mode, with --k3s-url) The real agent token to join
#                               with, used only if --k3s-token is not set.
#   --k3s-start                 (server/agent mode) Start and enable the K3s service
#                               immediately after install, instead of leaving it
#                               disabled/stopped. Useful when bootstrapping a cluster
#                               directly from the template; leave unset for Karpenter-
#                               managed worker templates, where Cloud-Init starts the
#                               service itself once the real config is written.
#
#   --cloudinit-drive           Attach a Proxmox Cloud-Init drive (scsi1) to the template
#                               (default: false — disabled)
#   --ciuser             USER   Cloud-Init user (requires --cloudinit-drive)
#   --cipassword         PWD    Cloud-Init password, plaintext as stored by Proxmox
#                               (requires --cloudinit-drive; prefer --sshkeys instead)
#   --sshkeys        KEY/PATH   Public SSH key for Cloud-Init (requires --cloudinit-drive).
#                               Accepts either a path to an existing public key file, or the
#                               key itself as a literal string (e.g. "ssh-ed25519 AAAA... user@host") —
#                               in the latter case it is written to a temporary file before being
#                               passed to 'qm set --sshkeys', which only accepts a file path.
#
# Examples:
#   ./build-ubuntu-k3s-template.sh -i 9000 -t
#   ./build-ubuntu-k3s-template.sh -c noble -i 9000 -n ubuntu24-k3s-agent-tpl -t -m agent
#   ./build-ubuntu-k3s-template.sh -c jammy -i 5000 -n k3s-master-01 -m server --k3s-token mySecretToken --k3s-start
#   ./build-ubuntu-k3s-template.sh -c noble -i 6000 -n k3s-worker-01 -m agent --k3s-url https://master.example.local:6443 --k3s-token mySecretToken --k3s-start
#   ./build-ubuntu-k3s-template.sh -c noble -i 9000 -n ubuntu24-base-tpl -t -s ssd-pool -d 50G -k v1.35.2+k3s1
#   ./build-ubuntu-k3s-template.sh -c jammy -i 5000 -n jammy-k3s-worker -t -v 10 -b vmbr1 \
#       --cloudinit-drive --ciuser admin --sshkeys ~/.ssh/id_ed25519.pub
#   ./build-ubuntu-k3s-template.sh -c jammy -i 5001 -t \
#       --cloudinit-drive --ciuser admin --sshkeys "ssh-ed25519 AAAAC3Nz... user@host"
# ----------------------------------------------------------------------------------

set -euo pipefail

# Privilege check (this script requires elevation)
if [[ "$EUID" -ne 0 ]]; then
    echo "Root privileges required — restarting with sudo..." >&2
    exec sudo "$0" "$@"
fi

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        -c|--codename)           CODENAME="$2";              shift 2 ;;
        -i|--vmid)               VMID="$2";                  shift 2 ;;
        -n|--name)               VM_NAME="$2";               shift 2 ;;
        -t|--template)           CONVERT_TO_TEMPLATE=true;   shift 1 ;;
        -s|--storage)            STORAGE="$2";               shift 2 ;;
        -v|--vlan)               VLAN="$2";                  shift 2 ;;
        -d|--disk)               DISKSIZE="$2";              shift 2 ;;
        -b|--bridge)             BRIDGE="$2";                shift 2 ;;
        -m|--k3s-mode)           K3S_MODE="$2";              shift 2 ;;
        -k|--k3sversion)         K3S_VERSION="$2";           shift 2 ;;
        --k3s-token)             K3S_TOKEN="$2";             shift 2 ;;
        --k3s-agent-token)       K3S_AGENT_TOKEN="$2";       shift 2 ;;
        --k3s-url)               K3S_URL_INPUT="$2";         shift 2 ;;
        --k3s-start)             K3S_START=true;             shift 1 ;;
        --cloudinit-drive)       WITH_CLOUDINIT_DRIVE=true;  shift 1 ;;
        --ciuser)                CIUSER="$2";                shift 2 ;;
        --cipassword)            CIPASSWORD="$2";            shift 2 ;;
        --sshkeys)               SSHKEYS_INPUT="$2";         shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# Default values (used only if not set via arguments)
CODENAME="${CODENAME:-noble}"
VM_NAME="${VM_NAME:-ubuntu24-k3s-worker}" # The name of the resulting VM or template
CONVERT_TO_TEMPLATE="${CONVERT_TO_TEMPLATE:-false}" # true = convert to template after build; false = leave as a regular VM
VLAN="${VLAN:-}" # The vlan tag for the template network interface, leave as empty string for no tag
DISKSIZE="${DISKSIZE:-30G}"
BRIDGE="${BRIDGE:-vmbr0}"
K3S_MODE="${K3S_MODE:-none}"    # agent | server | none
K3S_VERSION="${K3S_VERSION:-}"  # empty = latest stable
K3S_TOKEN="${K3S_TOKEN:-}"      # empty = generated by installer (server mode only)
K3S_AGENT_TOKEN="${K3S_AGENT_TOKEN:-}" # empty = no separate agent token configured
K3S_URL_INPUT="${K3S_URL_INPUT:-}" # empty = dummy URL is used (agent mode only)
K3S_START="${K3S_START:-false}" # true = start and enable service after install
WITH_CLOUDINIT_DRIVE="${WITH_CLOUDINIT_DRIVE:-false}"
CIUSER="${CIUSER:-}"
CIPASSWORD="${CIPASSWORD:-}"
SSHKEYS_INPUT="${SSHKEYS_INPUT:-}"

# Validate K3S_MODE
case "$K3S_MODE" in
    agent|server|none) ;;
    *) echo "Error: --k3s-mode must be one of: agent, server, none (got '$K3S_MODE')" >&2; exit 1 ;;
esac

# --k3s-token, --k3s-agent-token and --k3s-start only make sense when K3s is being installed
if [[ "$K3S_MODE" == "none" ]]; then
    [[ -n "$K3S_TOKEN" ]] && echo "Warning: --k3s-token has no effect when --k3s-mode is 'none'." >&2
    [[ -n "$K3S_AGENT_TOKEN" ]] && echo "Warning: --k3s-agent-token has no effect when --k3s-mode is 'none'." >&2
    [[ -n "$K3S_URL_INPUT" ]] && echo "Warning: --k3s-url has no effect when --k3s-mode is 'none'." >&2
    [[ "$K3S_START" == "true" ]] && echo "Warning: --k3s-start has no effect when --k3s-mode is 'none'." >&2
fi

# --k3s-url only makes sense in agent mode
if [[ "$K3S_MODE" != "agent" && -n "$K3S_URL_INPUT" ]]; then
    echo "Warning: --k3s-url is ignored outside of agent mode." >&2
fi

# In agent mode, --k3s-url requires at least one of --k3s-token / --k3s-agent-token
# (the real credentials), since joining a real cluster with a dummy token would fail
if [[ "$K3S_MODE" == "agent" && -n "$K3S_URL_INPUT" && -z "$K3S_TOKEN" && -z "$K3S_AGENT_TOKEN" ]]; then
    echo "Error: --k3s-url requires --k3s-token and/or --k3s-agent-token (the real credentials to join with)." >&2
    exit 1
fi

# In agent mode, --k3s-token takes priority over --k3s-agent-token if both are set
if [[ "$K3S_MODE" == "agent" && -n "$K3S_TOKEN" && -n "$K3S_AGENT_TOKEN" ]]; then
    echo "Warning: both --k3s-token and --k3s-agent-token were set in agent mode; --k3s-token takes priority." >&2
fi

# --k3s-token/--k3s-agent-token without --k3s-url in agent mode have no effect,
# since the dummy URL/token pair is always used together in that case
if [[ "$K3S_MODE" == "agent" && -z "$K3S_URL_INPUT" ]]; then
    [[ -n "$K3S_TOKEN" ]] && echo "Warning: --k3s-token is ignored in agent mode without --k3s-url (dummy URL/token pair is always used together)." >&2
    [[ -n "$K3S_AGENT_TOKEN" ]] && echo "Warning: --k3s-agent-token is ignored in agent mode without --k3s-url (dummy URL/token pair is always used together)." >&2
fi

# Validate Cloud-Init drive options
if [[ "$WITH_CLOUDINIT_DRIVE" != "true" ]]; then
    for var in CIUSER CIPASSWORD SSHKEYS_INPUT; do
        if [[ -n "${!var}" ]]; then
            echo "Error: --${var,,} requires --cloudinit-drive." >&2
            exit 1
        fi
    done
fi

# --sshkeys argument accepts either an existing file path or a literal key string.
# 'qm set --sshkeys' only accepts a file path, so a literal string is written
# to a temporary file before being passed through.
SSHKEYS_PATH=""
SSHKEYS_TMPFILE=""
if [[ -n "$SSHKEYS_INPUT" ]]; then
    if [[ -f "$SSHKEYS_INPUT" ]]; then
        SSHKEYS_PATH="$SSHKEYS_INPUT"
    else
        SSHKEYS_TMPFILE="$(mktemp)"
        echo "$SSHKEYS_INPUT" > "$SSHKEYS_TMPFILE"
        SSHKEYS_PATH="$SSHKEYS_TMPFILE"
    fi
fi

# Find all active storages that can host VM images
detect_storage() {
    local preselect="${1:-}"

    mapfile -t STORAGES < <(
        pvesm status --content images 2>/dev/null \
            | awk 'NR>1 && $3=="active" {print $1, $4, $5}'
    )

    if [[ ${#STORAGES[@]} -eq 0 ]]; then
        echo "Error: no active storage found for VM images." >&2
        exit 1
    fi

    # Validate preselected value if provided
    if [[ -n "$preselect" ]]; then
        for entry in "${STORAGES[@]}"; do
            if [[ "${entry%% *}" == "$preselect" ]]; then
                echo "$preselect"
                return
            fi
        done
        echo "Warning: storage '$preselect' not found or inactive." >&2
        echo "" >&2
    fi

    # Single storage — no prompt needed
    if [[ ${#STORAGES[@]} -eq 1 ]]; then
        echo "${STORAGES[0]%% *}"
        return
    fi

    # Multiple storages — show a menu
    echo "Available storages:" >&2
    echo "" >&2
    local i=1
    for entry in "${STORAGES[@]}"; do
        local name used total
        name=$(echo "$entry"  | awk '{print $1}')
        used=$(echo "$entry"  | awk '{print $2}')
        total=$(echo "$entry" | awk '{print $3}')
        printf "  [%d] %-20s used: %s / %s\n" "$i" "$name" "$used" "$total" >&2
        ((i++))
    done
    echo "" >&2

    local choice
    while true; do
        read -rp "Select storage [1-${#STORAGES[@]}]: " choice >&2
        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#STORAGES[@]} )); then
            echo "${STORAGES[$((choice-1))]%% *}"
            return
        fi
        echo "Invalid choice, please enter a number between 1 and ${#STORAGES[@]}." >&2
    done
}

STORAGE="$(detect_storage "${STORAGE:-}")"

if [[ -z "$STORAGE" ]]; then
    echo "Error: no active storage found for VM images. Use -s|--storage to specify one."
    exit 1
fi

# Check the required variables have been set
for var in CODENAME VMID VM_NAME STORAGE DISKSIZE BRIDGE
do
    if [[ -z "${!var}" ]]
    then
        echo "$var is not set"
        exit 1
    fi
done

# Fail early if the VMID is already in use, rather than after downloading and
# customizing the image
if qm status "$VMID" &>/dev/null; then
    echo "Error: VMID $VMID already exists on this node. Choose a different --vmid, or remove it first with 'qm destroy $VMID'." >&2
    exit 1
fi

# Check for libguestfs-tools
if [[ $(dpkg-query -W --showformat='${Status}\n' libguestfs-tools | grep "install ok installed") == "" ]]; then
    apt update -y
    apt install libguestfs-tools -y
fi

set -x

## If it doesn't already exist download a new $CODENAME image ie. https://cloud-images.ubuntu.com/kinetic/current/kinetic-server-cloudimg-amd64.img
## Links for newer/other images can be found here: https://cloud-images.ubuntu.com/, the .img you need should match the naming convention from the above line.
if [[ ! -f $CODENAME-server-cloudimg-amd64.img ]]; then
    wget https://cloud-images.ubuntu.com/${CODENAME}/current/${CODENAME}-server-cloudimg-amd64.img
fi

# Grab the name of the file
IMG=$(ls | grep ^${CODENAME}-server-cloudimg-amd64.img$)

NEWDISK=${CODENAME}.img

# Expand the image
virt-filesystems --long -h --all --format=raw -a $IMG
truncate -r $IMG $NEWDISK
truncate -s $DISKSIZE $NEWDISK
virt-resize --format raw --expand /dev/sda1 $IMG $NEWDISK

# ---------------------------------------------------------------------------
# Build the K3s firstboot-command according to --k3s-mode.
#
# "none"   no install step at all; K3s installation is left entirely to
#          Cloud-Init at provisioning time.
# "agent"  installs with either dummy or real join values. If --k3s-url is
#          set, --k3s-token takes priority over --k3s-agent-token if both
#          are given. Setting K3S_URL alone makes the installer default to
#          agent mode — appending "agent" explicitly is redundant but harmless.
# "server" installs in server mode. --k3s-token sets a known server token (if
#          omitted, the installer generates one itself). --k3s-agent-token
#          sets a separate, static agent-only token (see
#          https://docs.k3s.io/cli/token). If --k3s-token is given in secure
#          format (K10<ca-hash>::<user>:<password>) and --k3s-agent-token is
#          not explicitly set, only the <password> portion is extracted and
#          used as the agent token — valid per K3s docs, since the CA hash
#          and username are set internally regardless of what is passed on
#          the command line.
#
# In all modes, INSTALL_K3S_SKIP_START and INSTALL_K3S_SKIP_ENABLE are set
# unless --k3s-start is passed, in which case the service starts automatically
# after install (useful for bootstrapping a cluster directly from the template).
# ---------------------------------------------------------------------------
K3S_VERSION_ENV=""
if [[ -n "$K3S_VERSION" ]]; then
    K3S_VERSION_ENV="INSTALL_K3S_VERSION=${K3S_VERSION}"
fi

K3S_SKIP_ENV="INSTALL_K3S_SKIP_START=true INSTALL_K3S_SKIP_ENABLE=true"
if [[ "$K3S_START" == "true" ]]; then
    K3S_SKIP_ENV=""
fi

# Extracts the <password> portion from a token. Secure-format tokens
# (K10<ca-hash>::<user>:<password>) are split on the last ':'; short-format
# tokens (just <password>) are returned unchanged.
extract_token_password() {
    local token="$1"
    if [[ "$token" == *"::"* ]]; then
        echo "${token##*:}"
    else
        echo "$token"
    fi
}

K3S_FIRSTBOOT_ARGS=()
case "$K3S_MODE" in
    agent)
        K3S_URL_ENV="K3S_URL=${K3S_URL_INPUT:-https://dummy:6443}"
        if [[ -n "$K3S_TOKEN" ]]; then
            K3S_TOKEN_ENV="K3S_TOKEN=${K3S_TOKEN}"
        elif [[ -n "$K3S_AGENT_TOKEN" ]]; then
            K3S_TOKEN_ENV="K3S_TOKEN=${K3S_AGENT_TOKEN}"
        else
            K3S_TOKEN_ENV="K3S_TOKEN=dummy"
        fi
        K3S_FIRSTBOOT_ARGS=(--firstboot-command \
            "curl -sfL https://get.k3s.io | ${K3S_URL_ENV} ${K3S_TOKEN_ENV} ${K3S_SKIP_ENV} ${K3S_VERSION_ENV} sh -s - agent")
        ;;
    server)
        K3S_TOKEN_ENV=""
        [[ -n "$K3S_TOKEN" ]] && K3S_TOKEN_ENV="K3S_TOKEN=${K3S_TOKEN}"

        K3S_AGENT_TOKEN_ENV=""
        if [[ -n "$K3S_AGENT_TOKEN" ]]; then
            K3S_AGENT_TOKEN_ENV="K3S_AGENT_TOKEN=$(extract_token_password "$K3S_AGENT_TOKEN")"
        elif [[ -n "$K3S_TOKEN" ]]; then
            K3S_AGENT_TOKEN_ENV="K3S_AGENT_TOKEN=$(extract_token_password "$K3S_TOKEN")"
        fi

        K3S_FIRSTBOOT_ARGS=(--firstboot-command \
            "curl -sfL https://get.k3s.io | ${K3S_TOKEN_ENV} ${K3S_AGENT_TOKEN_ENV} ${K3S_SKIP_ENV} ${K3S_VERSION_ENV} sh -")
        ;;
    none)
        K3S_FIRSTBOOT_ARGS=()
        ;;
esac

# Configure the new img with K3s installed (per --k3s-mode) but disabled and
# not started. Cluster join operation will be initiated by Cloud-Init.
virt-customize \
        -a $NEWDISK \
        --install qemu-guest-agent,nfs-common,containerd,runc,curl \
        "${K3S_FIRSTBOOT_ARGS[@]}" \
        --truncate /etc/machine-id

# Build a vm with Qemu Guest Agent enabled, either kept as a regular VM or
# converted into a Proxmox template at the end, depending on -t/--template
qm create $VMID \
    --name $VM_NAME\
    --memory 2048 --balloon 2048 \
    --cpu cputype=host --cores 2 \
    --bios ovmf \
    --agent enabled=1

if [[ -n "$VLAN" ]]
then
    qm set $VMID --net0 virtio,bridge=$BRIDGE,firewall=1,tag=$VLAN
else
    qm set $VMID --net0 virtio,bridge=$BRIDGE,firewall=1
fi

# System disk
qm set $VMID \
    --efidisk0 $STORAGE:0 \
    --scsihw virtio-scsi-single \
    --scsi0 ${STORAGE}:0,import-from=$(realpath ${NEWDISK}),cache=writeback,discard=on,iothread=1,ssd=1 \
    --boot order=scsi0

# ---------------------------------------------------------------------------
# Optional Proxmox Cloud-Init drive (scsi1).
#
# Disabled by default. Only enable this if you are NOT using a separate
# Cloud-Init ISO (e.g. Karpenter's) to configure networking/users/SSH access —
# running both at once is redundant and the two sources can conflict.
# ---------------------------------------------------------------------------
if [[ "$WITH_CLOUDINIT_DRIVE" == "true" ]]; then
    qm set $VMID \
        --scsi1 $STORAGE:cloudinit \
        --ipconfig0 ip=dhcp

    [[ -n "$CIUSER" ]]       && qm set $VMID --ciuser "$CIUSER"
    [[ -n "$CIPASSWORD" ]]   && qm set $VMID --cipassword "$CIPASSWORD"
    [[ -n "$SSHKEYS_PATH" ]] && qm set $VMID --sshkeys "$SSHKEYS_PATH"
fi

# Clean up temporary SSH key file, if one was created
[[ -n "$SSHKEYS_TMPFILE" ]] && rm -f "$SSHKEYS_TMPFILE"

# Convert into a template, or start as a regular VM, depending on -t/--template
if [[ "$CONVERT_TO_TEMPLATE" == "true" ]]; then
    qm template $VMID
else
    qm start $VMID
fi

# Remove the image
rm $NEWDISK

if [[ "$CONVERT_TO_TEMPLATE" == "true" ]]; then
    echo "✓ Template $VM_NAME ($VMID) successfully created (Ubuntu $CODENAME, k3s-mode: $K3S_MODE, cloudinit-drive: $WITH_CLOUDINIT_DRIVE)."
else
    echo "✓ VM $VM_NAME ($VMID) successfully created and started (Ubuntu $CODENAME, k3s-mode: $K3S_MODE, cloudinit-drive: $WITH_CLOUDINIT_DRIVE)."
fi